smarthome/app/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('flats/', views.flats_list, name='flats-list'),
    path('tenants/', views.tenants_list, name='tenants'),
    path('flat/<int:pk>', views.FlatDetailView.as_view(), name='flat-detail'),
    path('flat/<int:flat_pk>/keypad', views.access_code, name='keypad'),
    path('room/<int:pk>', views.RoomDetailView.as_view(), name='room-detail'),
    path('room/<int:room_pk>/devices', views.host_device_permission, name='room-devices'),
    path('bye/', views.checkout, name='checkout'),

    path('change-state/<str:device_id>/<str:state>', views.change_device_state, name='change-state'),
    path('flat/<int:flat_pk>/code', views.change_access_code, name='change-code'),

    path('ajax/change_permission', views.ajax_change_device_permission, name='change-permission'),
    path('ajax/checkout-task', views.ajax_add_checkout_task, name='checkout-task'),
    path('ajax/validate-code', views.ajax_validate_access_code, name='validate-code'),
]

smarthome/smarthome/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('django.contrib.auth.urls')),
]

smarthome/app/templates/app/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="author" content="TokyoCommit">
    <title>{% block title %}IoT{% endblock %}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static 'app/css/mainpage.css' %}">
    <!-- material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <link href="{% static 'app/main.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'app/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'app/dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="{% static 'app/vendor/morrisjs/morris.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'app/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div>
            <a class="navbar-brand navbar-center" href="{%url 'app:index'%}"><img src=""></a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <a>Welcome, {{request.user.username}} !</a>
            <!-- /.dropdown -->
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="fa fa-user fa-fw">Home</i> <i class="fa fa-caret-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                    </li>
                    <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </ul>
                <!-- /.dropdown-user -->
            </li>
            <!-- /.dropdown -->
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a href="{% url 'app:flats-list' %}"><i class="fas fa-home"></i> Flats</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Profile<span class="fa arrow"></span></a>
                        <ul class="nav nav-second-level">
                            <li>
                                <a href="flot.html">Add permision for user</a>
                            </li>
                        </ul>
                        <!-- /.nav-second-level -->
                    </li>
                    <li>
                        <a href="{% url 'app:tenants'  %}"><i class="fa fa-table fa-fw"></i> Tenants </a>
                    </li>
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>


    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'app/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'app/vendor/metisMenu/metisMenu.min.js' %}"></script>

<!-- Morris Charts JavaScript -->
<script src="{% static 'app/vendor/raphael/raphael.min.js' %}"></script>
<script src="{% static 'app/vendor/morrisjs/morris.min.js' %}"></script>
<script src="{% static 'app/data/morris-data.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'app/dist/js/sb-admin-2.js' %}"></script>
<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
<div id="page-wrapper">
    {% block body %}
    {% endblock %}
</div>
</body>

<script>
{% block script %}
{% endblock %}
</script>


</html>

smarthome/app/templates/app/checking_out_list.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="TokyoCommit">
    <title>{% block title %}IoT{% endblock %}</title>

    <!-- material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

    <script src="{% static 'app/js/transition.min.js' %}"></script>

    <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'app/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <style>
        button {
            margin-top: 2rem;
        }
    </style>

</head>
<body style="margin-top: 5rem">
<div class="container">
    <div class="row">
        <div class="col-md-7">
            <div class="row">
                <h1 class="display-1">
                    Before you leave...
                </h1>
            </div>
            <div class="row list-group list-group-flush">
                {% for key, value in questions.items %}
                    <li id="btn{{ forloop.counter }}" type="button"
                        class="list-group-item list-group-item-action">
                        {{ key }}
                    </li>
                {% endfor %}
            </div>
            <button id="done" class="btn btn-outline-primary btn-lg">Done!</button>
            <script>
                $("#done").click(() => {
                    window.location.reload()
                })
            </script>
        </div>
        <!--<div class="col-md-5 float-right">-->
            <!--<img src="{% static 'app/img/bye.png' %}" class="img-responsive">-->
        <!--</div>-->
    </div>

</div>

</body>

</html>

smarthome/app/templates/app/flat.html
{% extends 'app/base.html' %}

{% block body %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">{{ flat.address }}{% if flat.host.profile.user.username == request.user.username %}<span
                class="badge badge-success">kod: {{flat.access_code}}</span>{%endif%}</h1>
    </div>
</div>
Rooms:
<div class="row">

    {% for room in rooms %}
    <div class="col-lg-3 col-md-6">
        {% if room.room_type == 'bathroom' %}
        <div class="panel panel-green">
            {% elif room.room_type == 'bedroom' %}
            <div class="panel panel-yellow">
                {% elif room.room_type == 'kitchen' %}
                <div class="panel panel-red">
                    {% else %}
                    <div class="panel panel-primary">
                        {% endif %}
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-6 col-sm-4">
                                    <div>
                                        <label>{{room.name.title}}</label>
                                    </div>
                                    {% if request.user.username == flat.host.profile.user.username %}
                                    <a href="{%url 'app:room-devices' room.pk %}">
                                    {% endif %}
                                        {% if room.room_type == 'bathroom' %}
                                        <img class="picsunder"
                                             src="https://www.shareicon.net/data/128x128/2016/06/27/787203_bathroom_512x512.png">
                                        {% elif room.room_type == 'bedroom' %}
                                        <img class="picsunder"
                                             src="https://www.shareicon.net/data/128x128/2016/07/31/804850_furniture_512x512.png">
                                        {% elif room.room_type == 'kitchen' %}
                                        <img class="picsunder"
                                             src="https://www.shareicon.net/data/128x128/2016/08/19/816881_tea_512x512.png">
                                        {% else %}
                                        <img class="picsunder"
                                             src="https://www.shareicon.net/data/128x128/2016/09/21/830512_business_512x512.png">
                                        {% endif %}
                                    {% if request.user.username == flat.host.profile.user.username %}
                                    </a>
                                   {% endif %}
                                    {% for device in room.devices %}
                                    <label>
                                        {% if room.room_type == 'bathroom' %}
                                        <input type="checkbox"

                                               {% if device.state %}checked{%endif%} data-toggle="toggle"
                                               data-onstyle="success">
                                        {% elif room.room_type == 'bedroom' %}
                                        <input type="checkbox" {% if device.state %}checked{%endif%}
                                               data-toggle="toggle" data-onstyle="warning">
                                        {% elif room.room_type == 'kitchen' %}
                                        <input type="checkbox" {% if device.state %}checked{%endif%}
                                               data-toggle="toggle" data-onstyle="danger">
                                        {% else %}
                                        <input type="checkbox" {% if device.state %}checked{%endif%}
                                               data-toggle="toggle">

                                        {% endif %}
                                        {{device.name}}</label>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endblock %}

smarthome/app/templates/app/flats_list.html
{% extends 'app/base.html' %}
{% block body %}
    <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Flats</h1>
                </div>
    </div>
    <div class="row">
    {% for flat in flats %}
    	<a href="{% url 'app:flat-detail' flat.pk %}">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            <div class="row">
                            <div class="col-xs room">
                            {% if flat.address == "Tokyo, Japan" %}
                            		<img class = "picsunder" src = "https://www.shareicon.net/data/128x128/2016/09/26/835059_buildings_512x512.png">
                            {% elif flat.address == "Berlin, Germany" %}
                            		<img class = "picsunder" src = "https://www.shareicon.net/data/128x128/2016/09/26/835063_buildings_512x512.png">
                            {% elif flat.address == "Warsaw, Poland" %}
                            		<img class = "picsunder" src = "https://www.shareicon.net/data/128x128/2016/09/26/835061_buildings_512x512.png">
                            {% else %}
                            		<img class = "picsunder" src = "https://www.shareicon.net/data/128x128/2016/09/26/835070_buildings_512x512.png">
                            {% endif %}
                            		<label></label>
                                    <label>Number of rooms: {{flat.rooms_number}}</label>
                                    <label>Address: {{flat.address}}</label>
                                    <label>Surface: {{flat.surface}} m<sup>2</sup></label>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
        </a>
    {% endfor %}
    </div>
{% endblock %}

smarthome/app/templates/app/keypad.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="TokyoCommit">
    <title>{% block title %}IoT{% endblock %}</title>

    <!-- material icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

    <script src="{% static 'app/vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'app/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <style>
        button {
            margin-top: 2rem;
        }
    </style>

</head>
<body style="margin-top: 5rem">
<div class="container">
    <h1 id="code" class="display-1">Enter the door code</h1>
    <table class="table-responsive">
        <tr>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="1" onclick="add(1)">1</button>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="2" onclick="add(2)">2</button>
            </td>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="3" onclick="add(3)">3</button>
            </td>
        </tr>
        <tr>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="1" onclick="add(4)">4</button>
            </td>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="2" onclick="add(5)">5</button>
            </td>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="3" onclick="add(6)">6</button>
            </td>
        </tr>
        <tr>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="1" onclick="add(7)">7</button>
            </td>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="2" onclick="add(8)">8</button>
            </td>
            <td>
                <button type="button" class="btn btn-info btn-lg" value="3" onclick="add(9)">9</button>
            </td>
        </tr>

    </table>
</div>

<script>
    var code = new String();

    function add(i) {
        code = code + i.toString();
        $("#code").text(code);
        if (code.length > 3) {
            console.log("send");
            $.ajax({
                    type: "GET",
                    url: '{% url "app:validate-code" %}',
                    data: {
                        "flat_id": {{flat_id}},
                        "code": code
                    },
                    success: function (response) {
                        console.log(response)
                        if (!response) {
                            code = "";
                            $("#code").text("Wrong code! Try again!");
                        } else {
                            $("#code").text("Welcome home!");
                        }
                    },
                    error: function (err) {
                        console.log("error");
                    }
                }
            )
        }
    }


</script>
</div>

</body>

</html>

smarthome/app/templates/app/room.html
{% extends 'app/base.html' %}

{% block body %}
<b>Room {{room.name}}</b></br>
    {% if permissions %}
Permissions:</br>
        {% for perm in permissions %}
            {{ perm }}
        {% endfor %}
    {% endif  %}
</br>
    {% if tasks %}
Checkout procedure:</br>
        {% for task in tasks %}
            {{ task }}
        {% endfor %}
    {% endif  %}
{% endblock %}

smarthome/app/templates/app/room_permissions.html
{% extends 'app/base.html' %}

{% block body %}
{% if devices %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">{{room.name}}</h1>
        </div>
        {% for device in devices %}
        <div>{{device.name}}</div>
        <input type="checkbox" data-toggle="toggle" data-on="Allow" data-off="Deny">
        <div><br>
            <div>
                {% endfor %}
            </div>
            <script>
    var code = new String();

    function change_perm(i) {
        <!--code = code + i.toString();-->
        <!--$("#code").text(code);-->
        <!--if (code.length > 3) {-->
            <!--console.log("send");-->
            $.ajax({
                    type: "GET",
                    url: '{% url "app:change-permission" %}',
                    data: {
                        "flat_id": {{flat_id}},
                        "code": code
                    },
                    success: function(response) {
                        console.log(response)
                        if (!response) {
                            code = "";
                            $("#code").text("Wrong code! Try again!");
                        } else {
                            $("#code").text("Welcome home!");
                        }
                    },
                    error: function(err) {
                        console.log("error");
                    }
                }
            )
        }
    }



            </script>
        </div>
        {% endif %}
        {% endblock %}

smarthome/app/templates/app/rooms_list.html
{% extends 'app/base.html' %}
{% block body %}
    {% for room in rooms %}
        <a href="{% url 'app:room-detail' room.pk %}" >{{ room.address }}</a>
    {% endfor %}
{% endblock %}

smarthome/app/templates/app/tenants.html
{% extends 'app/base.html' %}
{% block body %}
    <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Tenants</h1>
                </div>
    </div>
    <div class="row">
    {% for rent in rents %}
        <a href="{% url 'app:flat-detail' rent.flat.pk %}">
                <div class="col-lg-3 col-md-6">
                    <div class="panel panel-primary">
                        <div class="panel-heading rounded-circle">
                            <div class="row">
                            <div class="col-xs room">
                                    {% if rent.tenant.profile.user.username == 'Jack' or rent.tenant.profile.user.username == 'John' %}
                                            <img class = "picsunder" src = "https://www.shareicon.net/data/128x128/2016/08/18/814007_people_512x512.png">
                                    {% else %}
                                            <img class = "picsunder" src = "https://www.shareicon.net/data/128x128/2016/08/18/814001_people_512x512.png">
                                    {% endif %}
                                    <label></label>
                                    <label>Tenant name: {{rent.tenant.profile.user.username}}</label>
                                    <label>Begin date: {{rent.begin_date}}</label>
                                    <label>End date: {{rent.end_date}} </label>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
        </a>
    {% endfor %}
    </div>
{% endblock %}